# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: pygments

description: > # this means to ignore newlines until "baseurl:"
  
author:
  name: Robin Daugherty
  email: robin@robindaugherty.net
  github: RobinDaugherty
  twitter: robnich
  pinterest: robnich
  linkedin: robindaugherty
  bio: Software Developer
  email_md5: 726351295ec82e145928582f595aa3aa

categories_path: categories.html
tags_path: tags.html

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
