# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.robindaugherty.net"

# Build settings
markdown: kramdown
highlighter: pygments

assets:
  js_compressor:  uglifier
  css_compressor: sass

description: >
  Robin Daugherty is a software engineer.

author:
  name: Robin Daugherty
  email: robin@robindaugherty.net
  github: RobinDaugherty
  twitter: robnich
  pinterest: robnich
  linkedin: robindaugherty
  bio: Software engineer.
  email_md5: c03d217df4867dfb3b3674649fa92e5b

categories_path: categories.html
tags_path: tags.html

paginate: 10 # number of posts
paginate_path: "page:num"
exclude: ["README.md", "Gemfile", "Gemfile.lock", "Procfile", "unicorn.rb"]
